# Generated by Django 4.1.3 on 2022-11-26 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='Автор')),
                ('description', models.TextField(verbose_name='Описание')),
                ('whatsapp_number', models.CharField(max_length=15, verbose_name='Номер телефона(whatsapp)')),
                ('add_date', models.DateTimeField(auto_now=True, verbose_name='Дата добавление')),
            ],
            options={
                'verbose_name': 'Реклама',
                'verbose_name_plural': 'Рекламы',
            },
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_numbers', to='main.advert')),
            ],
            options={
                'verbose_name': 'Номер',
                'verbose_name_plural': 'Номера',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Фото')),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_images', to='main.advert')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
    ]
