# Generated by Django 4.1.3 on 2022-11-30 14:33

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='whatsapp_number',
            field=models.CharField(max_length=15, verbose_name='Номер телефона(whatsApp)'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='images'),
        ),
    ]
