# Generated by Django 4.1.3 on 2022-11-30 17:39

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='advert',
            name='itemchoice',
            field=models.CharField(choices=[('1', 'К.Мүлк'), ('2', 'Авто'), ('3', 'Мал чарба'), ('4', 'Алуу сатуу'), ('5', 'Жумуш'), ('6', 'Электроника'), ('7', 'Каттам')], default='New Item', max_length=50),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='images'),
        ),
    ]
