# Generated by Django 4.1.3 on 2022-12-01 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_advert_itemchoice_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='itemchoice',
            field=models.CharField(choices=[('1', 'К.Мүлк'), ('2', 'Авто'), ('3', 'Мал чарба'), ('4', 'Алуу сатуу'), ('5', 'Жумуш'), ('6', 'Электроника'), ('7', 'Каттам')], default='New Item', max_length=50, verbose_name='Тип'),
        ),
    ]
